run_name: 'week1'
run_mode: 'rcnn'
paths:
  annotations_path: '../dataset/ai_challenge_s03_c010-full_annotation.xml'
  video_path: '../../dataset/AICity_data/train/S03/c010/vdo.avi'
detections:
  rcnn: '../../dataset/AICity_data/train/S03/c010/det/det_mask_rcnn.txt'
  ssd: '../../dataset/AICity_data/train/S03/c010/det/det_ssd512.txt'
  yolo: '../../dataset/AICity_data/train/S03/c010/det/det_yolo3.txt'
